In [57]:
import pandas as pd
import numpy as np

In [58]:
df = pd.read_csv('credit_card.csv')
print(f"Sample of the dataset:\n{df.head()}\n")
print(f"Dimensions of the dataset: {df.shape}\n")
print(f"Summary statistics of the quantitative variables:\n{df.describe()}\n")

Sample of the dataset:
   gender  age        job  marital    education default housing loan  \
0  female   56  housemaid  married     basic.4y      no      no   no
1    male   57   services  married  high.school     yes      no   no
2  female   37   services  married  high.school      no     yes   no
3  female   40     admin.  married     basic.6y      no      no   no
4  female   56   services  married  high.school      no      no  yes

     contact CreditCard
0  telephone         no
1  telephone         no
2  telephone         no
3  telephone         no
4  telephone         no

Dimensions of the dataset: (41188, 10)

Summary statistics of the quantitative variables:
               age
count  41188.00000
mean      40.02406
std       10.42125
min       17.00000
25%       32.00000
50%       38.00000
75%       47.00000
max       98.00000

In [59]:
print(f"Summary statistics of the qualitative variables:\n{df.describe(include='object')}\n")

Summary statistics of the qualitative variables:
        gender     job  marital          education default housing   loan  \
count    41188   41188    41188              41188   41188   41188  41188
unique       2      12        4                  8       2       2      2
top     female  admin.  married  university.degree      no     yes     no
freq     20798   10422    24928              12168   32588   22566  33950

         contact CreditCard
count      41188      41188
unique         2          2
top     cellular         no
freq       26144      36548

In [60]:
# 1. What is the Probability that the Customer has a Credit Card ?
has_card = (df['CreditCard'] == 'yes').sum()
print(f"Number of customers with a credit card: {has_card}")

total_customers = df.shape[0]
print(f"Total number of customers: {total_customers}")

probability_has_card = has_card / total_customers
print(f"Probability that a customer has a credit card: {probability_has_card}\n")

Number of customers with a credit card: 4640
Total number of customers: 41188
Probability that a customer has a credit card: 0.11265417111780131

In [61]:
# 2. What is the Probability that the Customer age is greater than 50 ?
age_greater_50 = (df['age'] > 50).sum()
print(f"Number of customers with age greater than 50: {age_greater_50}")

probability_age_greater_50 = age_greater_50 / total_customers
print(f"Probability that a customer has age greater than 50: {probability_age_greater_50}\n")

Number of customers with age greater than 50: 7180
Probability that a customer has age greater than 50: 0.17432261823832185

In [62]:
# 3. What is the Probability that the Customer is illiterate ?
illiterate = (df['education'] == 'illiterate').sum()
print(f"Number of illiterate customers: {illiterate}")

probability_illiterate = illiterate / total_customers
print(f"Probability that a customer is illiterate: {probability_illiterate}\n")

Number of illiterate customers: 18
Probability that a customer is illiterate: 0.0004370204914052637

In [63]:
# 4. What is the Probability that the Customer has a Telephone ?
has_telephone = (df['contact'] == 'telephone').sum()
print(f"Number of customers with a telephone: {has_telephone}")

probability_has_telephone = has_telephone / total_customers
print(f"Probability that a customer has a telephone: {probability_has_telephone}\n")

Number of customers with a telephone: 15044
Probability that a customer has a telephone: 0.3652520151500437

In [64]:
# 5. What is the Probability that the Customer is Single and has a Credit Card ?
single_with_card = ((df['marital'] == 'single') & (df['CreditCard'] == 'yes')).sum()
print(f"Number of single customers with a credit card: {single_with_card}")

probability_single_with_card = single_with_card / total_customers
print(f"Probability that a customer is single and has a credit card: {probability_single_with_card}\n")

Number of single customers with a credit card: 1620
Probability that a customer is single and has a credit card: 0.03933184422647373

In [65]:
# 6. What is the Probability that the Customer is Male and has at most 6 Year of Education ?
male_has_education = ((df['gender'] == 'male') & ((df['education'] == 'basic.4y') | (df['education'] == 'basic.6y'))).sum()
print(f"Number of male customers with at most 6 years of education: {male_has_education}")

probability_male_has_education = male_has_education / total_customers
print(f"Probability that a customer is male and has at most 6 years of education: {probability_male_has_education}\n")

Number of male customers with at most 6 years of education: 3195
Probability that a customer is male and has at most 6 years of education: 0.0775711372244343

In [66]:
# 7. What is the Probability that the Customer is Retired and is divorced ?
retired_divorced = ((df['job'] == 'retired') & (df['marital'] == 'divorced')).sum()
print(f"Number of retired and divorced customers: {retired_divorced}")

probability_retired_divorced = retired_divorced / total_customers
print(f"Probability that a customer is retired and divorced: {probability_retired_divorced}\n")

Number of retired and divorced customers: 348
Probability that a customer is retired and divorced: 0.008449062833835098

In [69]:
# 8. Given the Customer has the credit card, find the probability that he/she is married
has_card_married = ((df['CreditCard'] == 'yes') & (df['marital'] == 'married')).sum()
print(f"Number of customers with a credit card who are married: {has_card_married}")

has_card_total = (df['CreditCard'] == 'yes').sum()
print(f"Total number of customers with a credit card: {has_card_total}")

probability_has_card_married = has_card_married / has_card_total
print(f"Probability that a customer is married given they have a credit card: {probability_has_card_married}\n")

Number of customers with a credit card who are married: 2532
Total number of customers with a credit card: 4640
Probability that a customer is married given they have a credit card: 0.5456896551724137

In [70]:
# 9. If a customer has a blue collar job, find the probability that he has a housing
has_job_housing = ((df['job'] == 'blue-collar') & (df['housing'] == 'yes')).sum()
print(f"Number of blue-collar customers with a housing loan: {has_job_housing}")

has_job = (df['job'] == 'blue-collar').sum()
print(f"Total number of blue-collar customers: {has_job}")

probability_has_job_housing = has_job_housing / has_job
print(f"Probability that a blue-collar customer has a housing loan: {probability_has_job_housing}\n")

Number of blue-collar customers with a housing loan: 4950
Total number of blue-collar customers: 9254
Probability that a blue-collar customer has a housing loan: 0.5349038253728118

# Part 2: Bayes Theorem

In [92]:
ds = pd.read_csv('kerala_floods.csv')
print(f"Sample of the dataset:\n{ds.head()}\n")
print(f"Dimensions of the dataset: {ds.shape}\n")
print(f"Number of missing values in each column:\n{ds.isnull().sum()}\n")

Sample of the dataset:
  SUBDIVISION  YEAR   JAN   FEB   MAR    APR    MAY     JUN     JUL    AUG  \
0      KERALA  1901  28.7  44.7  51.6  160.0  174.7   824.6   743.0  357.5
1      KERALA  1902   6.7   2.6  57.3   83.9  134.5   390.9  1205.0  315.8
2      KERALA  1903   3.2  18.6   3.1   83.6  249.7   558.6  1022.5  420.2
3      KERALA  1904  23.7   3.0  32.2   71.5  235.7  1098.2   725.5  351.8
4      KERALA  1905   1.2  22.3   9.4  105.9  263.3   850.2   520.5  293.6

     SEP    OCT    NOV    DEC   ANNUAL RAINFALL FLOODS
0  197.7  266.9  350.8   48.4            3248.6    YES
1  491.6  358.4  158.3  121.5            3326.6    YES
2  341.8  354.1  157.0   59.0            3271.2    YES
3  222.7  328.1   33.9    3.3            3129.7    YES
4  217.2  383.5   74.4    0.2            2741.6     NO

Dimensions of the dataset: (118, 16)

Number of missing values in each column:
SUBDIVISION         0
YEAR                0
JAN                 0
FEB                 0
MAR                 0
APR                 0
MAY                 0
JUN                 0
JUL                 0
AUG                 0
SEP                 0
OCT                 0
NOV                 0
DEC                 0
 ANNUAL RAINFALL    0
FLOODS              0
dtype: int64

In [93]:
# 1- We may start by preparing the required columns:
ds['june_more_than_500'] = (ds['JUN']>500).astype('int') #if more than 500, it will give one, other than that 0
ds['FLOODS_BIN'] = ds['FLOODS'].map({"YES":1,"NO":0})
ds.head()

,SUBDIVISION,YEAR,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANNUAL RAINFALL,FLOODS,june_more_than_500,FLOODS_BIN
0,KERALA,1901,28.7,44.7,51.6,160.0,174.7,824.6,743.0,357.5,197.7,266.9,350.8,48.4,3248.6,YES,1,1
1,KERALA,1902,6.7,2.6,57.3,83.9,134.5,390.9,1205.0,315.8,491.6,358.4,158.3,121.5,3326.6,YES,0,1
2,KERALA,1903,3.2,18.6,3.1,83.6,249.7,558.6,1022.5,420.2,341.8,354.1,157.0,59.0,3271.2,YES,1,1
3,KERALA,1904,23.7,3.0,32.2,71.5,235.7,1098.2,725.5,351.8,222.7,328.1,33.9,3.3,3129.7,YES,1,1
4,KERALA,1905,1.2,22.3,9.4,105.9,263.3,850.2,520.5,293.6,217.2,383.5,74.4,0.2,2741.6,NO,1,0

In [94]:
# 2- Select only the columns that will help to answer the main question.
data = ds[['june_more_than_500', 'FLOODS_BIN']]
print(data.head())

   june_more_than_500  FLOODS_BIN
0                   1           1
1                   0           1
2                   1           1
3                   1           1
4                   1           0

In [99]:
# 3- Create a cross tabulation for 'FLOODS' and 'June_more_than_500'
pd.crosstab(data['FLOODS_BIN'],data['june_more_than_500'],margins=True)

june_more_than_500   0   1  All
FLOODS_BIN
0                   19  39   58
1                    6  54   60
All                 25  93  118

In [100]:
# 4- What is the probability of a rainfall more than 500mm in June?
more_than_500 = (data['june_more_than_500'] == 1).sum()
total_rows = data.shape[0]
probability_more_than_500 = more_than_500 / total_rows
print(f"Probability of a rainfall more than 500mm in June: {probability_more_than_500}\n")

Probability of a rainfall more than 500mm in June: 0.788135593220339

In [102]:
# 5- What is the probability of having a flood?
have_flood = (data['FLOODS_BIN'] == 1).sum()
probability_have_flood = have_flood / total_rows
print(f"Probability of having a flood: {probability_have_flood}\n")

Probability of having a flood: 0.5084745762711864

In [106]:
# 6- What is the probability of having a flood and a rainfall more than 500mm in June?
have_flood_and_more_than_500 = ((data['FLOODS_BIN'] == 1) & (data['june_more_than_500'] == 1)).sum()
probability_have_flood_and_more_than_500 = have_flood_and_more_than_500 / total_rows
print(f"Probability of having a flood and a rainfall more than 500mm in June: {probability_have_flood_and_more_than_500}\n")

Probability of having a flood and a rainfall more than 500mm in June: 0.4576271186440678

In [107]:
# 7- What is the Probability of having a flood given it rained more than 500mm in June?
have_flood_given_more_than_500 = ((data['FLOODS_BIN'] == 1) & (data['june_more_than_500'] == 1)).sum()
total_more_than_500 = (data['june_more_than_500'] == 1).sum()
probability_have_flood_given_more_than_500 = have_flood_given_more_than_500 / total_more_than_500
print(f"Probability of having a flood given it rained more than 500mm in June: {probability_have_flood_given_more_than_500}\n")

Probability of having a flood given it rained more than 500mm in June: 0.5806451612903226

In [108]:
# 8- What is the probability of a rainfall less than 500mm in June?
less_than_500 = (data['june_more_than_500'] == 0).sum()
probability_less_than_500 = less_than_500 / total_rows
print(f"Probability of a rainfall less than 500mm in June: {probability_less_than_500}\n")

Probability of a rainfall less than 500mm in June: 0.211864406779661

In [109]:
# 9- What is probability of having a flood given that it rained less than 500mm?
have_flood_given_less_than_500 = ((data['FLOODS_BIN'] == 1) & (data['june_more_than_500'] == 0)).sum()
total_less_than_500 = (data['june_more_than_500'] == 0).sum()
probability_have_flood_given_less_than_500 = have_flood_given_less_than_500 / total_less_than_500
print(f"Probability of having a flood given it rained less than 500mm in June: {probability_have_flood_given_less_than_500}\n")

Probability of having a flood given it rained less than 500mm in June: 0.24

In [116]:
# 10- Answer this question by using Bayes Theorem and the law of the Total Probaility
P_A = (data['june_more_than_500'] == 1).sum() / data.shape[0]          # P(June > 500)
P_B = (data['FLOODS_BIN'] == 1).sum() / data.shape[0]               # P(Flood)

P_B_given_A = ((data['FLOODS_BIN'] == 1) & (data['june_more_than_500'] == 1)).sum() / (data['june_more_than_500'] == 1).sum()
P_A_given_B = (P_B_given_A * P_A) / P_B
print(f"Probability of having a rainfall more than 500mm in June given that there was a flood: {P_A_given_B}\n")

Probability of having a rainfall more than 500mm in June given that there was a flood: 0.9000000000000001

### 11- Answer this question by using Bayes Theorem only.
78% of the years with floods had rainfall in June > 500 mm.